# Generated by Django 6.1.1 on 2026-09-11 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nf_app', '0003_labels_notifications_projects_projectmembers_tasks_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activities',
            new_name='Activity',
        ),
        migrations.RenameModel(
            old_name='attachments',
            new_name='Attachment',
        ),
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
        migrations.RenameModel(
            old_name='Labels',
            new_name='Label',
        ),
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
        migrations.RenameModel(
            old_name='ProjectMembers',
            new_name='ProjectMember',
        ),
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
        migrations.RenameModel(
            old_name='TaskLabels',
            new_name='TaskLabel',
        ),
        migrations.RenameModel(
            old_name='Workspaces',
            new_name='Workspace',
        ),
        migrations.RenameModel(
            old_name='WorkspaceInvitations',
            new_name='WorkspaceInvitation',
        ),
        migrations.RenameModel(
            old_name='WorkspaceMembers',
            new_name='WorkspaceMember',
        ),
    ]
