# Generated by Django 6.1.1 on 2026-09-13 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nf_app', '0004_rename_activities_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspaceinvitation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='workspaceinvitation',
            name='token',
        ),
        migrations.AddField(
            model_name='workspaceinvitation',
            name='invited_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
