# Generated by Django 6.1.1 on 2026-09-23 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nf_app', '0005_remove_workspaceinvitation_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklabel',
            name='label',
        ),
        migrations.RemoveField(
            model_name='tasklabel',
            name='task',
        ),
        migrations.DeleteModel(
            name='Label',
        ),
        migrations.DeleteModel(
            name='TaskLabel',
        ),
    ]
